FROM rockylinux/rockylinux:8.6

ARG ART_USER
ARG ART_PASSWORD

SHELL ["/usr/bin/bash", "-c"]

RUN yum update -y \
    && yum install -y epel-release \
    && yum -y groupinstall "Development Tools" \
    && yum config-manager --set-enabled powertools \
    && yum install -y cmake3 gcc-toolset-14

RUN yum install -y git libzstd \
    && yum install -y patchelf \
    && yum install -y tzdata \
    && yum install -y wget unzip curl bzip2 xz \
    && yum install -y gcc gcc-c++ libatomic \
    && yum install -y double-conversion double-conversion-devel \
    && yum install -y make glibc-devel freetype-devel glib2-devel cairo-devel \
    && yum install -y perl perl-Digest-SHA perl-core zlib-devel \
    && yum install -y libffi-devel bzip2-devel readline-devel openssl-devel xz-devel \
    && yum install -y systemd-devel sqlite-devel pulseaudio-libs-devel \
    && yum install -y lld libudev-devel dbus-devel atk-devel at-spi2-atk-devel bison gperf \
    && yum install -y libicu libicu-devel \
    && yum install -y mesa-libGL-devel mesa-libGLU-devel mesa-libGLw-devel mesa-libEGL-devel \
    && yum install -y alsa-lib-devel alsa-plugins-pulseaudio alsa-utils audiofile-devel \
    && yum install -y PackageKit-gstreamer-plugin fontconfig-devel \
    && yum install -y gstreamer1-devel gstreamer1-plugins-base-devel gstreamer1-plugins-good \
    && yum install -y cups-devel libmng-devel libdrm libcap-devel nss-devel \
    && yum install -y libXcomposite-devel libXcursor-devel libXtst-devel libXScrnSaver \
    && yum install -y libXp-devel libXi-devel libXinerama-devel libXpm-devel libXrandr-devel \
    && yum install -y libXrender-devel libXext-devel libXfixes-devel libxshmfence-devel \
    && yum install -y flite-devel speech-dispatcher-devel libX11-devel libxkbcommon-devel \
    && yum install -y libxkbcommon-x11-devel libxcb-devel \
    && yum install -y xcb-util-keysyms-devel xcb-util-image-devel xcb-util-wm-devel \
    && yum install -y xcb-util-renderutil-devel xcb-util-cursor-devel libxkbfile-devel xcb-util-devel mtdev \
    && yum install -y at-spi2-core at-spi2-core-devel at-spi2-atk at-spi2-atk-devel \
    && yum install -y libjpeg-devel libjpeg-turbo-devel libtiff-devel lttng-ust \
    && yum install -y libproxy libstdc++-devel wayland-devel \
    && yum install -y postgresql-devel \
    && yum remove -y ninja-build \
    && yum remove -y nodejs \
    && yum clean all

RUN yum -y install --enablerepo=powertools libstdc++-static
RUN yum -y install glibc-langpack-en
     
# Download and install nodejs 20 LTS    
RUN curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -  \
    && yum -y install nsolid

# Download and extract OpenSSL 3.5.1 source code
RUN source /opt/rh/gcc-toolset-14/enable \
    && wget https://www.openssl.org/source/openssl-3.5.1.tar.gz \
    && tar -xf openssl-3.5.1.tar.gz \
    && cd openssl-3.5.1 \
    && ./config --prefix=/usr/local/openssl-3.5.1 --openssldir=/usr/local/openssl-3.5.1 \
    && make -j$(nproc) > /dev/null 2>&1 \
    && make install_sw \
    && rm -rf /openssl-3.5.1 /openssl-3.5.1.tar.gz \
    && echo "/usr/local/openssl-3.5.1/lib64" > /etc/ld.so.conf.d/openssl35.conf \
    && ldconfig

RUN wget https://github.com/ninja-build/ninja/releases/download/v1.11.1/ninja-linux.zip \
    && unzip ninja-linux.zip \
    && mv ninja /usr/local/bin \
    && rm -rf ninja-linux.zip

# Download the new version of zlib from artifactory
RUN wget --user="$ART_USER" --password="$ART_PASSWORD" -O zlib-headers.zip https://art-bobcat.autodesk.com:443/artifactory/autodesk-3p-nuget/External/zlib/1.1302.1/gec/zlib-headers.1.1302.1.nupkg && \
    unzip zlib-headers.zip -d zlib-headers && \
    mkdir -p /usr/local/zlib-1.3.2/include && \
    mv zlib-headers/inc/* /usr/local/zlib-1.3.2/include/ && \
    rm -rf zlib-headers.zip zlib-headers
RUN wget --user="$ART_USER" --password="$ART_PASSWORD" -O zlib-lib.zip https://art-bobcat.autodesk.com:443/artifactory/autodesk-3p-nuget/External/zlib/1.1302.1/gec/zlib-lib_linux-rocky8_release_intel64_gcc1121_static.1.1302.1.nupkg && \
    unzip zlib-lib.zip -d zlib-libs && \
    mkdir -p /usr/local/zlib-1.3.2/lib64 && \
    mv zlib-libs/libs/* /usr/local/zlib-1.3.2/lib64/ && \
    rm -rf zlib-lib.zip zlib-libs

# Download minizip
RUN wget --user="$ART_USER" --password="$ART_PASSWORD" -O minizip-headers.zip https://art-bobcat.autodesk.com:443/artifactory/autodesk-3p-nuget/External/zlib/1.1302.1/gec/minizip-headers.1.1302.1.nupkg && \
    unzip minizip-headers.zip -d minizip-headers && \
    mkdir -p /usr/local/minizip-1.3.2/include && \
    mv minizip-headers/inc/* /usr/local/minizip-1.3.2/include/ && \
    rm -rf minizip-headers.zip minizip-headers
RUN wget --user="$ART_USER" --password="$ART_PASSWORD" -O minizip-lib.zip https://art-bobcat.autodesk.com:443/artifactory/autodesk-3p-nuget/External/zlib/1.1302.1/gec/minizip-lib_linux-rocky8_release_intel64_gcc1121_static.1.1302.1.nupkg && \
    unzip minizip-lib.zip -d minizip-libs && \
    mkdir -p /usr/local/minizip-1.3.2/lib64 && \
    mv minizip-libs/libs/* /usr/local/minizip-1.3.2/lib64/ && \
    rm -rf minizip-lib.zip minizip-libs

# Build and install Python 3.13.12 from source using gcc-toolset-14
RUN source /opt/rh/gcc-toolset-14/enable \
    && wget -q -O /tmp/python.tar.xz https://www.python.org/ftp/python/3.13.12/Python-3.13.12.tar.xz \
    && tar -xf /tmp/python.tar.xz -C /tmp \
    && cd /tmp/Python-3.13.12 \
    && PKG_CONFIG_PATH="/usr/local/openssl-3.5.1/lib64/pkgconfig" \
       CPPFLAGS="-I/usr/local/zlib-1.3.2/include -I/usr/local/openssl-3.5.1/include" \
       LDFLAGS="-L/usr/local/zlib-1.3.2/lib64 -L/usr/local/openssl-3.5.1/lib64 -Wl,-rpath,/usr/local/zlib-1.3.2/lib64 -Wl,-rpath,/usr/local/openssl-3.5.1/lib64" \
       ./configure --prefix=/usr/local --with-openssl=/usr/local/openssl-3.5.1 --with-openssl-rpath=auto \
    && make -j$(nproc) \
    && make altinstall \
    && ln -sf /usr/local/bin/python3.13 /usr/local/bin/python3 \
    && ln -sf /usr/local/bin/pip3.13 /usr/local/bin/pip3 \
    && cd / && rm -rf /tmp/python.tar.xz /tmp/Python-3.13.12 \
    && python3 -m pip install --no-cache-dir html5lib dataclasses \
        --index-url https://art-toucan.autodesk.com/artifactory/api/pypi/autodesk-pypi-virtual/simple \
        --extra-index-url https://ue1.artifactory.autodesk.com/artifactory/api/pypi/autodesk-pypi-virtual/simple

# when install libatomic, the libatomic.so cannot be created which cause link error due to libatomic missing
RUN ln -sf /usr/lib64/libatomic.so.1 /usr/lib64/libatomic.so

# Clean up to reduce image size
RUN yum clean all

RUN git config --system credential.helper store \
    && mkdir /root/.ssh \
    && ssh-keyscan git.autodesk.com > /root/.ssh/known_hosts
COPY .git-credentials /root/

WORKDIR /src
COPY . /src

ENTRYPOINT ["scl", "enable", "gcc-toolset-14", "--", "adsk-build-scripts/BuildQtOnRocky.sh"]
