FROM autodesk-docker.art-bobcat.autodesk.com/engops/gecoss/qt5/ubuntu-2204-gcc11:nightly

# Download and extract OpenSSL 3.5.1 source code
RUN wget https://www.openssl.org/source/openssl-3.5.1.tar.gz && \
    tar -xf openssl-3.5.1.tar.gz && \
    cd openssl-3.5.1 && \
    ./config --prefix=/usr/local/openssl-3.5.1 --openssldir=/usr/local/openssl-3.5.1 && \
    make > /dev/null 2>&1 && \
    make install_sw && \
    rm -rf openssl-3.5.1 openssl-3.5.1.tar.gz

RUN git config --system credential.helper store \
    && mkdir /root/.ssh \
    && ssh-keyscan git.autodesk.com > /root/.ssh/known_hosts
COPY .git-credentials /root/
WORKDIR /src
COPY . /src
ENTRYPOINT ["adsk-build-scripts/BuildQtOnLinux.sh"]
