---
# README
# Please use 2 spaces, 
# indentation is sensitive
---
# Mapping: Label to Packing Variables
windows:
  qt5.win.debug:
  - x64 debug
  qt5.win.release:
  - x64 release
mac:
  qt5.mac:
  - universal
linux:
  qt5.lnx.ubuntu22.debug:
  - ubuntu22 debug gcc11
  qt5.lnx.ubuntu22.release:
  - ubuntu22 release gcc11
  qt5.lnx.rocky86.debug:
  - rocky86 debug gcc10
  qt5.lnx.rocky86.release:
  - rocky86 release gcc10
---
# Variables
variables:
  component_name: qt-lgpl
platforms:
  windows:
    variables:
      osName: win
      toolchain: v140
    configurations:
      release:
        variables:
          config: release
      debug:
        variables:
          config: debug
      x64:
        variables:
          compiler: intel64
  mac:
    variables:
      osName: osx-14.0
    configurations:
      universal:
        variables:
          compiler: ubx64arm64
          toolchain: clang700
          config: release
  linux:
    variables:
      osName: linux
    configurations:
      release:
        variables:
          config: release
      debug:
        variables:
          config: debug
      ubuntu22:
        variables:
          distro: ubuntu22
      rocky86:
        variables:
          distro: rocky8
      gcc11:
        variables:
          compiler: intel64
          toolchain: gcc11
      gcc10:
        variables:
          compiler: intel64
          toolchain: gcc10
---
# Nuspec Definition
linux:
- type: nupkg
  nuspec_file: ${component_name}.nuspec
  version: "${pkg_version}"
  adsk_xml_template: "adsk.xml.tpl"
  packages:
  - id: ${component_name}-headers_${osName}_${compiler}
    sources:
    - include: "${build_dir}/${config}/include/**/*"
      exclude: ''
      target: "inc"
    dependencies: []
  - id: ${component_name}-resources_${osName}-${distro}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/resources/**/*"
      exclude: ''
      target: "resources"
    dependencies: []
  - id: ${component_name}_${osName}-${distro}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/bin/**/*"
      exclude: '*.debug'
      target: "bin"
    preserve_symlink: false
    dependencies: 
    - package_name: ${component_name}-translations
      version: "${pkg_version}"
    - package_name: ${component_name}-plugins_${osName}-${distro}_${config}_${compiler}_${toolchain}
      version: "${pkg_version}"
  - id: ${component_name}-compilers_${osName}-${distro}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/compilers/**/*"
      exclude: ''
      target: "compilers"
    - include: "${build_dir}/${config}/mkspecs/**/*"
      exclude: ''
      target: "mkspecs"
    preserve_symlink: false
    dependencies: []
  - id: ${component_name}-lib_${osName}-${distro}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/lib/**/*"
      exclude: '*.debug'
      target: "libs"
    - include: "${build_dir}/${config}/metatypes/**/*"
      exclude: ''
      target: "metatypes"
    preserve_symlink: false
    dependencies: 
    - package_name: ${component_name}-headers_${osName}_${compiler}
      version: "${pkg_version}"
    - package_name: ${component_name}_${osName}-${distro}_${config}_${compiler}_${toolchain}
      version: "${pkg_version}"
  - id: ${component_name}-plugins_${osName}-${distro}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/plugins/**/*"
      exclude: ''
      target: "plugins"
    preserve_symlink: false
    dependencies: []
  - id: ${component_name}-qml_${osName}-${distro}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/qml/**/*"
      exclude: ''
      target: "qml"
    preserve_symlink: false
    dependencies: []
  - id: ${component_name}-webengine_${osName}-${distro}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/libexec/QtWebEngineProcess*"
      exclude: ''
      target: "libexec"
    preserve_symlink: false
    dependencies: 
    - package_name: ${component_name}-resources_${osName}-${distro}_${toolchain}
      version: "${pkg_version}"
  - id: ${component_name}-sym_${osName}-${distro}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/bin/**/*.debug"
      exclude: ''
      target: "bin"
    - include: "${build_dir}/${config}/lib/**/*.debug"
      exclude: ''
      target: "libs"
    - include: "${build_dir}/${config}/libexec/**/*.debug"
      exclude: ''
      target: "libexec"
    dependencies: [] 
- type: zip
  version: "${pkg_version}"
  adsk_xml_template: "adsk.xml.tpl"
  packages:
  - id: ${component_name}_${osName}-${distro}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/**/*"
      exclude: ''
      target: "${pkg_version}"
windows:
- type: nupkg
  nuspec_file: ${component_name}.nuspec
  version: "${pkg_version}"
  adsk_xml_template: "adsk.xml.tpl"
  packages:
  - id: ${component_name}-translations
    sources:
    - include: "${build_dir}/${config}/translations/**/*"
      exclude: ''
      target: "bin"
    dependencies: []
  - id: ${component_name}-headers_${osName}_${compiler}
    sources:
    - include: "${build_dir}/${config}/include/**/*"
      exclude: ''
      target: "inc"
    dependencies: []
  - id: ${component_name}-resources_${osName}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/resources/**/*"
      exclude: ''
      target: "resources"
    dependencies: []
  - id: ${component_name}_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/bin/**/*"
      exclude: '*.pdb'
      target: "bin"
    dependencies: 
    - package_name: ${component_name}-translations
      version: "${pkg_version}"
    - package_name: ${component_name}-plugins_${osName}_${config}_${compiler}_${toolchain}
      version: "${pkg_version}"
  - id: ${component_name}-sym_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/bin/**/*.pdb"
      exclude: ''
      target: "bin"
    - include: "${build_dir}/${config}/lib/**/*.pdb"
      exclude: ''
      target: "libs"
    dependencies: []  
  - id: ${component_name}-compilers_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/compilers/**/*"
      exclude: ''
      target: "compilers"
    - include: "${build_dir}/${config}/mkspecs/**/*"
      exclude: ''
      target: "mkspecs"
    dependencies: []
  - id: ${component_name}-lib_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/lib/cmake/**/*"
      exclude: ''
      target: "libs/cmake"
    - include: "${build_dir}/${config}/lib/**/*"
      exclude: '*.pdb'
      target: "libs"
    - include: "${build_dir}/${config}/metatypes/**/*"
      exclude: ''
      target: "metatypes"
    dependencies: 
    - package_name: ${component_name}-headers_${osName}_${compiler}
      version: "${pkg_version}"
    - package_name: ${component_name}_${osName}_${config}_${compiler}_${toolchain}
      version: "${pkg_version}"
  - id: ${component_name}-plugins_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/plugins/**/*"
      exclude: ''
      target: "plugins"
    dependencies: []
  - id: ${component_name}-qml_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/qml/**/*"
      exclude: ''
      target: "qml"
    dependencies: []
  - id: ${component_name}-webengine_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/bin/QtWebEngineProcess*.exe"
      exclude: ''
      target: "bin"
    dependencies: 
    - package_name: ${component_name}-resources_${osName}_${toolchain}
      version: "${pkg_version}"
- type: zip
  version: "${pkg_version}"
  adsk_xml_template: "adsk.xml.tpl"
  packages:
  - id: ${component_name}_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/**/*"
      exclude: ''
      target: "${pkg_version}"      
mac:
- type: nupkg
  nuspec_file: ${component_name}.nuspec
  version: "${pkg_version}"
  adsk_xml_template: "adsk.xml.tpl"
  packages:
  - id: ${component_name}-headers_${osName}_${compiler}
    sources:
    - include: "${build_dir}/${config}/include/**/*"
      exclude: ''
      target: "inc"
    dependencies: []
  - id: ${component_name}_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/bin/**/*"
      exclude: '*.dSYM'
      target: "bin"
    dependencies: 
    - package_name: ${component_name}-translations
      version: "${pkg_version}"
    - package_name: ${component_name}-plugins_${osName}_${config}_${compiler}_${toolchain}
      version: "${pkg_version}"
  - id: ${component_name}-compilers_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/compilers/**/*"
      exclude: ''
      target: "compilers"
    - include: "${build_dir}/${config}/mkspecs/**/*"
      exclude: ''
      target: "mkspecs"
    dependencies: []
  - id: ${component_name}-lib_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/lib/**/*"
      exclude: '*.dSYM'
      target: "libs"
    - include: "${build_dir}/${config}/metatypes/**/*"
      exclude: ''
      target: "metatypes"
    dependencies: 
    - package_name: ${component_name}-headers_${osName}_${compiler}
      version: "${pkg_version}"
    - package_name: ${component_name}_${osName}_${config}_${compiler}_${toolchain}
      version: "${pkg_version}"
  - id: ${component_name}-plugins_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/plugins/**/*"
      exclude: ''
      target: "plugins"
    dependencies: []
  - id: ${component_name}-qml_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/qml/**/*"
      exclude: ''
      target: "qml"
    dependencies: []
  - id: ${component_name}-webengine_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/lib/QtWebEngineCore.framework/**/*"
      exclude: ''
      target: "libs/QtWebEngineCore.framework"
    - include: "${build_dir}/${config}/lib/QtWebEngineWidgets.framework/**/*"
      exclude: ''
      target: "libs/QtWebEngineWidgets.framework"
    - include: "${build_dir}/${config}/lib/QtWebEngineQuick.framework/**/*"
      exclude: ''
      target: "libs/QtWebEngineQuick.framework"
    - include: "${build_dir}/${config}/lib/QtWebEngineQuickDelegatesQml.framework/**/*"
      exclude: ''
      target: "libs/QtWebEngineQuickDelegatesQml.framework"
    dependencies: []
  - id: ${component_name}-sym_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/bin/**/*.dSYM/**"
      exclude: ''
      target: "bin"
    - include: "${build_dir}/${config}/lib/**/*.dSYM/**"
      exclude: ''
      target: "libs"
    - include: "${build_dir}/${config}/libexec/**/*.dSYM/**"
      exclude: ''
      target: "libexec"
    dependencies: [] 
- type: zip
  version: "${pkg_version}"
  adsk_xml_template: "adsk.xml.tpl"
  packages:
  - id: ${component_name}_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/**/*"
      exclude: ''
      target: "${pkg_version}"    
...
