---
# README
# Please use 2 spaces, 
# indentation is sensitive
---
# Mapping: Label to Packing Variables
windows:
  qt5.win.debug:
  - x64 debug
  qt5.win.release:
  - x64 release
mac:
  qt5.mac:
  - universal
linux:
  qt5.lnx.ubuntu22.debug:
  - ubuntu22 debug gcc11
  qt5.lnx.ubuntu22.release:
  - ubuntu22 release gcc11
  qt5.lnx.rocky86.debug:
  - rocky86 debug gcc10
  qt5.lnx.rocky86.release:
  - rocky86 release gcc10
---
# Variables
variables:
  component_name: qt-lgpl
platforms:
  windows:
    variables:
      osName: win
      toolchain: v140
    configurations:
      release:
        variables:
          config: release
      debug:
        variables:
          config: debug
      x64:
        variables:
          compiler: intel64
  mac:
    variables:
      osName: osx-14.0
    configurations:
      universal:
        variables:
          compiler: ubx64arm64
          toolchain: clang700
          config: release
  linux:
    variables:
      osName: linux
    configurations:
      release:
        variables:
          config: release
      debug:
        variables:
          config: debug
      ubuntu22:
        variables:
          distro: ubuntu22
      rocky86:
        variables:
          distro: rocky8
      gcc11:
        variables:
          compiler: intel64
          toolchain: gcc11
      gcc10:
        variables:
          compiler: intel64
          toolchain: gcc10
---
# Nuspec Definition
linux:
- type: zip
  version: "${pkg_version}"
  adsk_xml_template: "adsk.xml.tpl"
  packages:
  - id: ${component_name}_${osName}-${distro}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/**/*"
      exclude: ''
      target: "${pkg_version}"
windows:
- type: zip
  version: "${pkg_version}"
  adsk_xml_template: "adsk.xml.tpl"
  packages:
  - id: ${component_name}_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/**/*"
      exclude: ''
      target: "${pkg_version}"
mac:
- type: zip
  version: "${pkg_version}"
  adsk_xml_template: "adsk.xml.tpl"
  packages:
  - id: ${component_name}_${osName}_${config}_${compiler}_${toolchain}
    sources:
    - include: "${build_dir}/${config}/**/*"
      exclude: ''
      target: "${pkg_version}"
...
